# Generated by Django 5.0.2 on 2024-02-14 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=100)),
                ('admin_email', models.EmailField(max_length=254, unique=True)),
                ('admin_address', models.CharField(max_length=200)),
                ('admin_password', models.CharField(max_length=100)),
                ('admin_acc_created_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
