# Generated by Django 5.0.3 on 2024-03-25 08:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_voter_id', models.BinaryField()),
                ('encrypted_candidate_id', models.BinaryField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_hash', models.BinaryField()),
                ('block_hash', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('party', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(default=0, max_length=255)),
                ('votes', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/candidates/')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionResult',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('election_name', models.CharField(max_length=255)),
                ('candidate_name', models.CharField(max_length=255)),
                ('total_votes', models.IntegerField()),
                ('result_declaration_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ElectionResultStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_declared', models.BooleanField(default=False)),
                ('result_calculated', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='EncryptionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='VotePhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('registration', 'Registration'), ('voting', 'Voting'), ('closed', 'Closed')], default='registration', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('voter_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('dob', models.DateField()),
                ('password', models.CharField(max_length=128)),
                ('is_registered', models.BooleanField(default=False)),
                ('has_voted', models.BooleanField(default=False)),
            ],
        ),
    ]
